const tab =
	'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';

export default {
	aboutUs: 'About Us',
	add: 'ADD',
	admin: 'Admin',
	areYouSure: 'Are you sure?',
	back: 'back',
	cancel: 'Cancel',
	chooseAFile: 'Choose a file...',
	confirm: 'Confirm',
	coordinate: 'Coordinate',
	credit: {
		copyrightBy:
			'Developed by Piya Limpiti, Pheereeya boonchiyapruek, Nitipak Samsen, Ratthapon Wittayasattikul, Tapanon Amatayakul',
		supportedBy: 'Supported by Creative Economy Agency (Public Organization)',
		title: 'Credit',
	},
	date: 'Date',
	dateTime: {
		endDate: 'End Date',
		endTime: 'End Time',
		selectEndDate: 'Select End Date',
		selectStartDate: 'Select Start Date',
		selectEndTime: 'Select End Time',
		selectStartTime: 'Select Start Time',
		startDate: 'Start Date',
		startTime: 'Start Time',
	},
	densityList: 'Density List',
	densityListTitle: 'Density List',
	description: `Crowd check assists in journey planning, prior to and on site, with real-time density which equally disclosing the information to the public. To do so, it measures the crowd density by capturing real-time Bluetooth signals, representing number of people, and analyse the number in relation to location's capacity.`,
	detail: 'Detail',
	email: 'Email',
	exceed: 'Exceed',
	id: 'ID',
	legend: {
		avoid:
			'Exceed capacity of the venue. "Now is not the right time, <strong>AVOID</strong> joining the crowd"',
		find: 'Find where you are',
		go: '75% capacity of the venue. "Enough space, <strong>GO</strong> and have some fun"',
		goAhead:
			'50% capacity of the venue. "Plenty of space, <strong>GO AHEAD!</strong>, best time for a good shot"',
		legendAndSuggestion: 'Legend and suggested action',
		title: 'Legend',
		wait: 'Max capacity of the venue. "Compact space, <strong>WAIT A WHILE</strong> before entry"',
		zoom: 'Zoom in for spacific location',
	},
	link: 'Link',
	linkDestination: 'http://www.crowdcheck.info/',
	linkTo: 'Link to',
	locationName: 'Location Name',
	owner: 'Exhibitor',
	password: 'Password',
	place: {
		avoid: 'Avoid!',
		go: 'Go',
		goAhead: 'Go Ahead!',
		wait: 'Wait a while',
	},
	pleaseSelectAnImageFile: 'Please select an image file (png or jpg)',
	pointOfInterest: {
		cafeAndRestaurant: 'Cafe & Restaurant',
		craft: 'Craft',
		designStudio: 'Design studio',
		fashion: 'Fashion',
		gallery: 'Gallery',
		parking: 'Parking',
		title: 'Point Of Interest',
	},
	privacy: {
		content: `${tab}As the density information is determined by the counting of device's Bluetooth signal available in such area. It does not request the access to personal information. Also the data is forwarded directly to the cloud server, reducing privacy risks. Therefore this platform is secure and does not require access to any personal information.`,
		title: 'Privacy',
	},
	programName: 'Program name',
	programNotFound: 'Program not found at this period.',
	programType: {
		creativeMarket: 'Creative market',
		event: 'Event',
		promotion: 'Promotion',
		showcase: 'Showcase',
		showcaseAndExhibition: 'Showcase & exhibition',
		talk: 'Talk',
		title: 'program type',
		tour: 'Tour',
		workshop: 'Workshop',
	},
	projectBackground: {
		content: `${tab}Distribution of density is an important tool in restricting coronavirus (COVID-19). Op-portunist therefore develop this project as part of the preventive measures and hopefully rebuilding trust in public space as the common ground of city dwellers.<br />${tab}Crowd check is a web-base platform which informs crowd density at public venue. Crowd check assists in journey planning, prior to and on site, with real-time density which equally disclosing the information to the public. To do so, it measures the crowd density by capturing real-time Bluetooth signals, representing number of people, and analyse the number in relation to location's capacity.`,
		title: 'Project Background',
	},
	signIn: 'Sign In',
	somethingWentWrong: 'something went wrong',
	suggestionPlace: 'Suggestion Place',
	time: 'Time',
	travelSuggestion: {
		content_1: `1. Check information on the outbreak of COVID 19 in the country from the website of the Department of Disease Control. <a href='https://covid19.ddc.moph.go.th' target='_blank'>https://covid19.ddc.moph.go.th</a>.`,
		content_2: `2. Inform contact information for agencies that assist in the occurrence of illness or emergency while traveling: hospital call 02-3539800-1 police station call 02-234-0242, 02-233-7420 festival information center call 02-105-7400`,
		content_3: `3. People with chronic diseases Immunocompromised, young children and the elderly be cautious when entering crowded areas and in contact with others.`,
		content_4: `4. Choose accommodation, restaurant or tourist attractions Certified for Safety and Health Administration standard :SHA`,
		content_5: `5. Recommend traveling on dates and times that are not crowded would reduce the risk of infection from others`,
		content_6: `6. Activities that involve large groups of people, in an enclose and air conditioning area, should be avoided.`,
		content_7: `7. While traveling, recommended to wear a medical mask or cloth mask at all times`,
		content_8: `8. When traveling to various places in the community, register the entry and exit at the designated point.`,
		title: `Travel suggestion`,
		more: `More information on the guidelines for the prevention of COVID-19 by the Department of Disease Control at <a href='https://ddc.moph.go.th/viralpneumonia/file/int_protection/int_protection_070164.pdf' target='_blank'>https://ddc.moph.go.th/viralpneumonia/file/int_protection/int_protection_070164.pdf</a>`,
	},
	trend: {
		daysAgo: 'days ago',
		today: 'Today',
		yesterday: 'Yesterday',
	},
	update: 'update',
	uploadImage: 'Upload Image',
	username: 'Username',
	venue: 'Venue',
	venueName: 'Venue Name',
	venueTrendRecord: 'Venue Trend Record',
};
