name: build-and-push
on:
  push:
    branches:
      - "ci-fix-push"
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=wannadev/crowdcheck-ui
          TAGS="${DOCKER_IMAGE}-${GITHUB_SHA::8}"
          echo ::set-output name=tags::${TAGS}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prep.outputs.tags }}
